// eslint-disable-next-line import/no-anonymous-default-export
export default [
  // ---------------- SIMILARITY MATCHING QUESTIONS ----------------
  {
    qid: 'early-night',
    question: 'Are you an early bird or night owl?',
    type: 'options',
    answers: ['Early', 'Night'],
    matchType: 'similarity',
    button: 'Next',
  },
  {
    qid: 'cleanliness',
    question: 'How important is cleanliness to you?',
    type: 'options',
    answers: ['Low', 'Medium', 'High'],
    matchType: 'similarity',
    button: 'Next',
  },
  {
    qid: 'daily-routine',
    question: 'Do you prefer a fixed daily routine?',
    type: 'options',
    answers: ['Yes', 'No'],
    matchType: 'similarity',
    button: 'Next',
  },
  {
    qid: 'quiet-room',
    question: 'Do you prefer a quiet room environment?',
    type: 'options',
    answers: ['Yes', 'No'],
    matchType: 'similarity',
    button: 'Next',
  },
  {
    qid: 'study-style',
    question: 'Individual study or group study?',
    type: 'options',
    answers: ['Individual', 'Group'],
    matchType: 'similarity',
    button: 'Next',
  },
  {
    qid: 'gaming',
    question: 'Do you enjoy gaming in your free time?',
    type: 'options',
    answers: ['Yes', 'No'],
    matchType: 'similarity',
    button: 'Next',
  },
  {
    qid: 'stress-handle-sim',
    question: 'How do you handle stress?',
    type: 'options',
    answers: ['Stay calm', 'Need support'],
    matchType: 'similarity',
    button: 'Next',
  },
  {
    qid: 'movies-frequency',
    question: 'How often do you watch movies/TV shows?',
    type: 'options',
    answers: ['Never', 'Rarely', 'Sometimes', 'Frequently'],
    matchType: 'similarity',
    button: 'Next',
  },
  {
    qid: 'friends-other-rooms',
    question: 'How do you feel about having a friend over in other rooms?',
    type: 'options',
    answers: ['Good', 'Bad'],
    matchType: 'similarity',
    button: 'Next',
  },
  {
    qid: 'sharing-items',
    question: 'How comfortable are you with sharing personal items?',
    type: 'options',
    answers: ['Not comfortable', 'Somewhat', 'Very comfortable'],
    matchType: 'similarity',
    button: 'Next',
  },

  // ---------------- COMPLEMENTARY MATCHING QUESTIONS ----------------
  {
    qid: 'social-level',
    question: 'How social are you?',
    type: 'options',
    answers: ['Introvert', 'Ambivert', 'Extrovert'],
    matchType: 'complementary',
    button: 'Next',
  },
  {
    qid: 'group-lead',
    question: 'Do you usually take the lead in group activities?',
    type: 'options',
    answers: ['Yes', 'No'],
    matchType: 'complementary',
    button: 'Next',
  },
  {
    qid: 'stress-handle-comp',
    question: 'How do you handle stress?',
    type: 'options',
    answers: ['Stay calm', 'Need support'],
    matchType: 'complementary',
    button: 'Next',
  },
  {
    qid: 'decision-style',
    question: 'How do you make decisions?',
    type: 'options',
    answers: ['Emotional', 'Logical'],
    matchType: 'complementary',
    button: 'Next',
  },
  {
    qid: 'adaptability',
    question: 'How adaptable are you to different personalities?',
    type: 'options',
    answers: ['Low', 'Medium', 'High'],
    matchType: 'complementary',
    button: 'Next',
  },
  {
    qid: 'difficult-situations',
    question: 'In difficult situations, you are more likely to:',
    type: 'options',
    answers: ['Reassure others', 'Seek reassurance'],
    matchType: 'complementary',
    button: 'Next',
  },
  {
    qid: 'wake-up-style',
    question: 'Preferred way to wake up?',
    type: 'options',
    answers: ['Alarm', 'Self wake up'],
    matchType: 'complementary',
    button: 'Next',
  },
  {
    qid: 'conversation-style',
    question: 'During conversation, you usually:',
    type: 'options',
    answers: ['Mostly listen', 'Mostly speak'],
    matchType: 'complementary',
    button: 'Next',
  },
  {
    qid: 'exam-period',
    question: 'During exam periods, you usually:',
    type: 'options',
    answers: ['Remind Timeline', 'Rely on reminders'],
    matchType: 'complementary',
    button: 'Next',
  },

  // ---------------- FINAL SCREEN ----------------
  {
    qid: 'final',
    question: 'Thanks for sharing! We will find the best match for you.',
    type: 'final',
    answers: ['Okay'],
    button: 'Finish',
  },
];
